{
  "hash": "309f7db51386dac7e6f20df5bc7c8a7b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 2: Thailand Drug Abuse\"\nauthor: \"Bao Jie Yeo\"\ndate: '2024-10-13'\ndate-modified: '2024-10-13'\nexecute: \n  eval: true\n  echo: true\n  freeze: true\n---\n\n\nThis exercise aims to analyze the spatial distribution of drug offenses in Thailand from 2017 to 2022. Geospatial analysis techniques will be employed to understand the patterns of drug offenses across provinces and identify any spatial clustering or autocorrelation in the data.\n\n## 1.0 Introduction\n\n## 2.0 Data Collection\n\n### 2.1 Thailand Drug Offense Data\n\nThe dataset from [Kaggle](https://www.kaggle.com/datasets/thaweewatboy/thailand-drug-offenses-2017-2022) contains information on drug offenses in Thailand from 2017 to 2022. The original data is sourced from the [Office of the Narcotics Control Board](https://data.oncb.go.th/casePer).\n\n### 2.2 GIS Data\n\nRelevant [Geospatial data](https://data.humdata.org/dataset/cod-ab-tha?) was gathered from [Humanitarian Data Exchange (HDX)](https://data.humdata.org/)\n\n## 3.0 Data Wrangling\n\n### 3.1 Loading Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse, knitr, viridis, patchwork, gridExtra, kableExtra, sfdep, tmap, tmaptools, patchwork, scales, gganimate, rayshader, spdep, ggrepel)\n```\n:::\n\n\n### 3.2 Loading Data\n\nTo aid in our analysis, two sets of data will be imported:\n\n1. **Drug Offense Data**: This Kaggle dataset examines statistics related to different types of drug offenses in Thailand, categorized by fiscal year. The data was sourced from the Office of the Narcotics Control Board.\n2. **Provincial Boundary Data**: These shapefiles from Humanitarian Data Exchange (HDX) contain the provincial boundaries of Thailand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_offenses_unfiltered <- read_csv(\"data/aspatial/thai_drug_offenses_2017_2022.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 7392 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): types_of_drug_offenses, province_th, province_en\ndbl (2): fiscal_year, no_cases\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n**Exploring the Drug Offenses Data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(drug_offenses_unfiltered, n=10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   fiscal_year types_of_drug_offenses no_cases province_th   province_en        \n         <dbl> <chr>                     <dbl> <chr>         <chr>              \n 1        2017 drug_use_cases            11871 กรุงเทพมหานคร  Bangkok            \n 2        2017 drug_use_cases              200 ชัยนาท         Chai Nat           \n 3        2017 drug_use_cases              553 นนทบุรี         Nonthaburi         \n 4        2017 drug_use_cases              450 ปทุมธานี        Pathum Thani       \n 5        2017 drug_use_cases              378 พระนครศรีอยุธยา Phra Nakhon Si Ayu…\n 6        2017 drug_use_cases              727 ลพบุรี          Loburi             \n 7        2017 drug_use_cases              820 สมุทรปราการ    Samut Prakan       \n 8        2017 drug_use_cases               69 สระบุรี         Saraburi           \n 9        2017 drug_use_cases              127 สิงห์บุรี         Sing Buri          \n10        2017 drug_use_cases              208 อ่างทอง        Ang Thong          \n```\n\n\n:::\n:::\n\n\nA glimpse of the dataset reveals some interesting points. There are actually multiple types of drug offenses being examined here, though it definitely seems like the dominant type is `drug_use_cases`. We also have access to the number of cases for each province for fiscal years 2017 to 2022.\n\n**Loading Shapefiles**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm1_unfiltered <- st_read(\"data/adms\", layer = \"tha_admbnda_adm1_rtsd_20220121\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `tha_admbnda_adm1_rtsd_20220121' from data source \n  `C:\\Users\\yeoba\\Desktop\\bjyeo\\IS415-GeospatialAnalytics\\TakehomeEx\\THE02\\data\\adms' \n  using driver `ESRI Shapefile'\nSimple feature collection with 77 features and 16 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nWe check if there are any missing rows for our our drug offenses dataset. Thankfully, it seems like there aren't any.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_filled <- all(!is.na(drug_offenses_unfiltered$province_th) & !is.na(drug_offenses_unfiltered$province_en))\nprint(all_filled)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_offenses <- drug_offenses_unfiltered %>%\n  mutate(province_en = case_when(\n    province_en == \"buogkan\" ~ \"Bueng Kan\",\n    province_en == \"Loburi\" ~ \"Lop Buri\",\n    TRUE ~ province_en\n  ))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_offenses <- drug_offenses %>% select(-province_th)\nadm1 <- adm1_unfiltered %>% select(-ADM1_TH, -ADM1ALT1TH, -ADM1ALT2TH, -ADM0_TH, \n                                   -ADM0_EN, -ADM1ALT1EN, -ADM1ALT2EN)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_totals <- drug_offenses %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE))\n\nadm1_data <- adm1 %>%\n  left_join(province_totals, by = c(\"ADM1_EN\" = \"province_en\"))\n```\n:::\n\n\n### 3.3 Exploratory Data Analysis\n\n**Overall Map**\n\nThe choropleth map of Thailand below shows the distribution of drug use cases across provinces. The color intensity represents the number of cases, with darker shades indicating higher numbers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoropleth_map <- ggplot(adm1_data) +\n   geom_sf(aes(fill = total_cases)) +\n   scale_fill_viridis(\n     option = \"plasma\",\n     name = \"Number of Cases\",\n    trans = \"log10\",\n     breaks = scales::breaks_log(n = 5),\n     labels = scales::label_number(accuracy = 1)\n   ) +\n   theme_minimal() +\n   labs(\n     title = \"Drug Use Cases in Thailand (2017-2022)\",\n     subtitle = \"Distribution across provinces\"\n   ) +\n   theme(\n     plot.title = element_text(size = 16, face = \"bold\", hjust = 0.5),\n     plot.title.position = \"plot\",\n     plot.subtitle = element_text(size = 12, hjust = 0.5),\n     legend.position = \"right\",\n     axis.text.x = element_text(angle = 45, hjust = 1),\n     panel.grid.major = element_line(color = \"white\")\n   )\n\nprint(choropleth_map)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\n1. The **Northern and Northeastern** provinces of Thailand exhibit a notably higher concentration of drug use cases. Border provinces often face more significant challenges related to cross-border drug trafficking, which could explain the concentration.\n2. While the Northern and parts of Central Thailand display the highest number of cases, the Southern provinces and a few other parts of the country have a considerably lower concentration of cases.\n\n**Drug Offenses by Fiscal Year**\n\nNext, we want to visualize how the number of drug offenses has evolved over the years. This line plot will help us identify any trends or patterns in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyearly_totals <- drug_offenses %>%\n  group_by(fiscal_year) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE))\n\ntemporal_plot <- ggplot(yearly_totals, aes(x = fiscal_year, y = total_cases)) +\n  geom_line(aes(group = 1), color = \"blue\", alpha = 0.7) +\n  geom_point(color = \"blue\", size = 3) +\n  geom_smooth(aes(group = 1), formula = y ~ x, method = \"loess\", se = TRUE, \n              color = \"red\", fill = \"pink\", alpha = 0.3, linewidth = 1.2) +\n  labs(title = \"Trend of Drug Offense Cases in Thailand (2017-2022)\",\n       x = \"Year\", y = \"Number of Cases\") +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    axis.title = element_text(size = 12),\n    legend.position = \"none\"\n  ) +\n  scale_y_continuous(labels = scales::comma) +\n  scale_x_continuous(breaks = seq(min(yearly_totals$fiscal_year), max(yearly_totals$fiscal_year), by = 1))\n\nprint(temporal_plot)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\nThe number of drug offense cases in Thailand has exhibited a **fluctuating pattern** between 2017 and 2022. The graph shows an **overall upward trend until 2021**, followed by a significant drop in 2022.\n\n**Animated Choropleth Map**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyearly_province_totals <- drug_offenses %>%\n  group_by(province_en, fiscal_year) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE), .groups = 'drop')\n\nadm1_data_yearly <- adm1 %>%\n  left_join(yearly_province_totals, by = c(\"ADM1_EN\" = \"province_en\"))\n\nanimated_choropleth <- ggplot(adm1_data_yearly) +\n  geom_sf(aes(fill = total_cases)) +\n  scale_fill_viridis_c(\n    option = \"plasma\",\n    name = \"Number of Cases\",\n    trans = \"log10\",\n    breaks = scales::breaks_log(n = 5),\n    labels = scales::label_number(accuracy = 1)\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"Drug Use Cases in Thailand\",\n    subtitle = \"Fiscal Year: {current_frame}\"\n  ) +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 14, hjust = 0.5),\n    legend.position = \"right\",\n    axis.text.x = element_blank(),\n    axis.text.y = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank()\n  ) +\n  gganimate::transition_manual(fiscal_year) +\n  gganimate::ease_aes('linear')\n\n# animated_choropleth_render <- gganimate::animate(animated_choropleth, \n#                                       nframes = length(unique(adm1_data_yearly$fiscal_year)), \n#                                       fps = 1, \n#                                       width = 800, \n#                                       height = 600)\n# \n# gganimate::anim_save(\"animated_choropleth_drug_offenses.gif\", animated_choropleth_render)\n```\n:::\n\n\n![Animated Choropleth Map of Drug Offenses in Thailand](animated_choropleth_drug_offenses.gif)\n\nKey Observations:\n\nThe animated choropleth map provides a **dynamic visualization** of how drug offenses have evolved across provinces in Thailand from 2017 to 2022. The fluctuating patterns and changes in the intensity of cases over the years are clearly visible. In particular, 2019 and 2021 are where the two peaks of drug offenses are observed.\n\n**Highest Drug Offense Cases by Province**\n\nWe've seen the overall distribution of drug offenses. Let's now take a more focused approach and identify the provinces with the highest number of drug offense cases. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_totals <- drug_offenses %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>%\n  arrange(desc(total_cases)) %>%\n  top_n(15, total_cases)\n\nbar_chart <- ggplot(province_totals, aes(x = reorder(province_en, total_cases), y = total_cases, fill = total_cases)) +\n  geom_bar(stat = \"identity\") +\n  coord_flip() +\n  scale_fill_viridis(option = \"D\", direction = -1) +\n  labs(\n    title = \"Top 15 Provinces with Highest Drug Offense Cases\",\n    x = \"Province\",\n    y = \"Total Number of Cases\",\n    fill = \"Total Cases\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.y = element_text(size = 8)\n  ) +\n  scale_y_continuous(labels = scales::comma)\n\nprint(bar_chart)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\n1. Bangkok has the highest number of drug offense cases by a significant margin. This is likely due to its high population density, and its role as a major hub for transportation, trade, and organized crime activities.\n2. The southern provinces of Nakhon Si Thammarat and Songkhla also report high numbers of drug offenses. These provinces might experience high drug-related activity due to their geographic location near drug trafficking routes, particularly in the south where drug smuggling may be more prevalent.\n3. Many of the provinces with high numbers of drug offenses, such as Surat Thani, Chon Buri, and Samut Prakan, are located in central and southern Thailand. This could suggest these regions are hotspots for drug-related activity, possibly due to their access to ports, highways, and urban centers that facilitate drug distribution.\n\n**Examining Types of Drug Offenses**\n\nEarlier, we noticed that there are multiple types of drug offenses in the dataset. Let's explore the different types of drug offenses and their distribution across provinces. But first, we need to conduct some data preprocessing; the offense types are a little awkwardly named in the original dataset, and thus somewhat difficult to interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noffense_names <- c(\n  \"conspiracy_cases\" = \"Conspiracy\",\n  \"drug_use_cases\" = \"Drug Use\",\n  \"export_cases\" = \"Export\",\n  \"import_cases\" = \"Import\",\n  \"possession_cases\" = \"Possession\",\n  \"possession_with_intent_to_distribute_cases\" = \"Possession with Intent to Distribute\",\n  \"production_cases\" = \"Production\",\n  \"trafficking_cases\" = \"Trafficking\"\n)\n\nrename_suspects <- function(x) {\n  ifelse(\n    str_starts(x, \"suspects_in_\"),\n    paste0(\"Suspects (\", offense_names[str_remove(x, \"suspects_in_\")], \")\"),\n    x\n  )\n}\n\ndrug_offenses_cleaned <- drug_offenses %>%\n  mutate(\n    types_of_drug_offenses = case_when(\n      types_of_drug_offenses %in% names(offense_names) ~ offense_names[types_of_drug_offenses],\n      TRUE ~ types_of_drug_offenses\n    ),\n    types_of_drug_offenses = rename_suspects(types_of_drug_offenses)\n  )\n\nunique_offenses <- unique(drug_offenses_cleaned$types_of_drug_offenses)\nprint(\"Updated Types of Drug Offenses:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Updated Types of Drug Offenses:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (offense in sort(unique_offenses)) {\n  print(offense)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Conspiracy\"\n[1] \"Drug Use\"\n[1] \"Export\"\n[1] \"Import\"\n[1] \"Possession\"\n[1] \"Possession with Intent to Distribute\"\n[1] \"Production\"\n[1] \"Suspects (Conspiracy)\"\n[1] \"Suspects (Drug Use)\"\n[1] \"Suspects (Export)\"\n[1] \"Suspects (Import)\"\n[1] \"Suspects (Possession with Intent to Distribute)\"\n[1] \"Suspects (Possession)\"\n[1] \"Suspects (Production)\"\n[1] \"Suspects (Trafficking)\"\n[1] \"Trafficking\"\n```\n\n\n:::\n:::\n\n\n**Distribution of Drug Offenses by Type**\n\nWe explore the distribution of drug offenses by type.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noffense_types_summary <- drug_offenses_cleaned %>%\n  filter(!grepl(\"^Suspects\", types_of_drug_offenses)) %>%\n  group_by(types_of_drug_offenses) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>%\n  arrange(desc(total_cases))\n\n# Create bar graph\nbar_graph <- ggplot(offense_types_summary, aes(x = reorder(types_of_drug_offenses, -total_cases), y = total_cases, fill = total_cases)) +\n  geom_bar(stat = \"identity\") +\n  scale_fill_viridis_c(option = \"viridis\") +\n  labs(\n    title = \"Types of Drug Offenses in Thailand\",\n    x = \"Type of Offense\",\n    y = \"Total Number of Cases\",\n    fill = \"Total Cases\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    plot.title = element_text(size = 14),\n    legend.position = \"right\"\n  ) +\n  scale_y_continuous(labels = scales::comma)\n\nprint(bar_graph)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\nOf the types of drug offenses, **Drug Use and Possession** are the most common offenses reported in Thailand. Whereas, **Trafficking and Production** offenses are less frequent. This distribution suggests that there are more people involved in the consumption and possession of drugs than in the production and trafficking of drugs.\n\n**Top Drug Offenses Across Years**\n\nLet's examine how the numbers for drug use and possession have evolved across the years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_3_offenses <- drug_offenses_cleaned %>%\n  filter(!grepl(\"^Suspects\", types_of_drug_offenses)) %>%\n  group_by(types_of_drug_offenses) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE)) %>%\n  top_n(3, total_cases) %>%\n  pull(types_of_drug_offenses)\n\nyearly_top_3_offenses <- drug_offenses_cleaned %>%\n  filter(types_of_drug_offenses %in% top_3_offenses) %>%\n  group_by(fiscal_year, types_of_drug_offenses) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE), .groups = 'drop')\n\nline_chart <- ggplot(yearly_top_3_offenses, aes(x = fiscal_year, y = total_cases, color = types_of_drug_offenses)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 3) +\n  scale_color_viridis_d(option = \"viridis\") +\n  labs(\n    title = \"Top 3 Types of Drug Offenses Across Years\",\n    x = \"Fiscal Year\",\n    y = \"Total Number of Cases\",\n    color = \"Type of Offense\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 14),\n    legend.position = \"bottom\"\n  ) +\n  scale_y_continuous(labels = scales::comma)\n\nprint(line_chart)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\n1. **Drug Use** cases have consistently been the most prevalent type of drug offense across all years. There are two noticeable peaks in 2019 and 2021, which is congruent with the overall trend of drug offenses we observed earlier.\n2. **Possession** cases have shown a gradual general decline over the years. This could indicate a shift in law enforcement focus or changes in drug-related activities in the country.\n3. **Possession with Intent to Distribute** cases have remained relatively stable over the years, with a significant decrease in 2022. This type of drug offense is less common, which is expected given the nature of the offense.\n\n**Scatter-Plot Analysis: Suspects vs. Offenses**\n\nLet's not forget that in our data, we also have access to the number of suspects for each type of drug offense. We can utilize that data to create a scatter plot that compares the number of suspects to the number of offenses across provinces.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_data <- drug_offenses_cleaned %>%\n  group_by(province_en, types_of_drug_offenses) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE), .groups = 'drop') %>%\n  mutate(\n    category = if_else(str_starts(types_of_drug_offenses, \"Suspects\"), \"Suspects\", \"Offenses\"),\n    base_offense = if_else(\n      str_starts(types_of_drug_offenses, \"Suspects\"),\n      str_remove(types_of_drug_offenses, \"Suspects \\\\(|\\\\)\"),\n      types_of_drug_offenses\n    )\n  ) %>%\n  pivot_wider(\n    names_from = category,\n    values_from = total_cases,\n    values_fill = list(total_cases = 0)\n  ) %>%\n  group_by(province_en) %>%\n  summarize(\n    Suspects = sum(Suspects, na.rm = TRUE),\n    Offenses = sum(Offenses, na.rm = TRUE)\n  ) %>%\n  mutate(Total = Suspects + Offenses) %>%\n  top_n(5, Total)\n\nscatter_plot <- ggplot(plot_data, aes(x = Offenses, y = Suspects)) +\n  geom_point(aes(size = Offenses + Suspects, color = Suspects / Offenses), alpha = 0.7) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_text_repel(\n    aes(label = province_en), \n    size = 3, \n    max.overlaps = 10, \n    box.padding = 0.5\n  ) +\n  scale_x_log10(labels = scales::comma_format()) +\n  scale_y_log10(labels = scales::comma_format()) +\n  scale_size_continuous(range = c(2, 10), guide = \"none\") +\n  scale_color_viridis_c(option = \"plasma\", name = \"Suspect to Offense Ratio\") +\n  labs(\n    title = \"Drug-Related Suspects vs. Offenses by Province\",\n    x = \"Number of Offenses (log)\",\n    y = \"Number of Suspects (log)\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 14),\n    axis.title = element_text(size = 10)\n  ) +\n  coord_equal()\n\nprint(scatter_plot)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\n1. Points above the line: The top five provinces are all located above the dashed line. This indicates that in each of these provinces, the number of drug-related suspects exceeds the number of drug offenses. In other words, for each reported offense, more than one individual is implicated or suspected.\n2. Potential multi-suspect cases: Since the number of suspects is higher than the number of offenses, it can be inferred that many drug-related cases involve multiple individuals working together. This could suggest a pattern of drug offenses that are often collaborative in nature, such as trafficking, distribution rings, or group involvement in drug use or sales.\n3. Bangkok's Prominent Role: Bangkok shows the highest number of both suspects and offenses, with a considerable lead over other provinces. This reinforces the idea that drug-related activities in Bangkok are substantial and likely involve more organized criminal groups with multiple participants per offense.\n\n## 4.0 Global Measures of Spatial Autocorrelation (GMSA)\n\n### 4.1 Methodology\n\nBefore we proceed with the analysis, let's outline the steps we will follow:\n\n1. **Temporal Focus**: As shown in the graphs earlier, there are 2 significant peaks in drug offenses in 2019 and 2021. We will also be considering the first year, 2017 to observe the trend over the years.\n2. **Drug Offense Types**: We will focus on the total number of drug offenses across provinces for each year. This prevents us from having tunnel-vision on a specific type of drug offense.\n\n### 4.2 Distribution of Drug Offenses\n\nWe start by plotting the choropleth maps for the selected years (2017, 2019, 2021) to visualize the distribution of drug offenses across provinces.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_years <- c(2017, 2019, 2021)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_offenses_2017 <-  drug_offenses_cleaned %>%\n  filter(fiscal_year == 2017) %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_2017_data <- adm1 %>%\n  left_join(drug_offenses_2017, by = c(\"ADM1_EN\" = \"province_en\"))\n\nmap_2017 <- tm_shape(map_2017_data) +\n  tm_fill(\"total_cases\", title = \"Number of Cases\", style = \"quantile\") +\n  tm_borders() +\n  tm_layout(title = \"Drug Offenses in Thailand (2017)\",\n            legend.outside = TRUE)\n\nmap_2017\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_offenses_2019 <-  drug_offenses_cleaned %>%\n  filter(fiscal_year == 2019) %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_2019_data <- adm1 %>%\n  left_join(drug_offenses_2019, by = c(\"ADM1_EN\" = \"province_en\"))\n\nmap_2019 <- tm_shape(map_2019_data) +\n  tm_fill(\"total_cases\", title = \"Number of Cases\", style = \"quantile\") +\n  tm_borders() +\n  tm_layout(title = \"Drug Offenses in Thailand (2019)\",\n            legend.outside = TRUE)\n\nmap_2019\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndrug_offenses_2021 <-  drug_offenses_cleaned %>%\n  filter(fiscal_year == 2021) %>%\n  group_by(province_en) %>%\n  summarize(total_cases = sum(no_cases, na.rm = TRUE))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_2021_data <- adm1 %>%\n  left_join(drug_offenses_2021, by = c(\"ADM1_EN\" = \"province_en\"))\n\nmap_2021 <- tm_shape(map_2021_data) +\n  tm_fill(\"total_cases\", title = \"Number of Cases\", style = \"quantile\") +\n  tm_borders() +\n  tm_layout(title = \"Drug Offenses in Thailand (2021)\",\n            legend.outside = TRUE)\n\nmap_2021\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nKey Observations on Drug Offenses in Thailand (2017, 2019, 2021):\n\n1. **General Temporal Trends**:\n  * 2017: The initial distribution of drug offenses shows a more moderate concentration across the country, with fewer provinces experiencing very high levels of offenses. The highest concentrations appear in southern Thailand and central regions near Bangkok.\n  * 2019: By 2019, the overall number of drug offenses seems to have risen significantly in certain provinces, particularly in the southern and northeastern regions are more prevalent than in 2017. The central region, near Bangkok, also shows increased activity.\n  * 2021: In 2021, drug offenses remain highly concentrated, but there appears to be some redistribution. The northeastern region continues to show a high number of offenses, while some provinces that were less affected in 2017 are now more heavily impacted. Interestingly, southern Thailand still shows persistent high levels of offenses.\n2. **Regional Consistencies**:\n  * Southern Thailand: Throughout all three years, southern Thailand consistently shows high levels of drug offenses. Provinces like Surat Thani, Nakhon Si Thammarat, and areas in the deep south maintain their darker colors across the years, indicating a persistent issue with drug-related activities. This suggests a long-standing problem with either drug trafficking or local demand in this region.\n  * Central Thailand and Bangkok Area: The provinces surrounding Bangkok maintain moderate to high drug offense levels, indicating that the capital and its surrounding areas are key hubs for drug-related activities.\n  * Northeastern Region: The northeastern provinces remain consistently problematic. \n3. **Notable Shifts**:\n  * 2019 Spike: The 2019 map shows a noticeable increase in drug offenses compared to 2017. More provinces in the northeast, central, and southern regions see elevated cases of drug offenses.\n  * 2021 Redistribution: By 2021, while drug offenses remain high, there are some noticeable shifts. Some central provinces that showed higher concentrations in 2019 seem to experience a slight decrease by 2021. However, the northeastern and southern regions remain heavily impacted.\n\n### 4.3 Moran's I Analysis\n\n**Moran's I** is a measure of spatial autocorrelation that evaluates whether the values of a variable are clustered, dispersed, or randomly distributed across space. It ranges from -1 (dispersed) to 1 (clustered) with 0 indicating spatial randomness. \n\nFirst, a seed is set for reproducibility.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\n```\n:::\n\n\nNext, we define a function to correct any missing neighbors in the spatial data. Then, we calculate the Moran's I statistic and perform a Monte Carlo simulation to test the null hypothesis of spatial randomness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrect_neighbors <- function(map_data, fiscal_year) {\n  suppressWarnings(\n    nb <- st_contiguity(map_data)\n  )\n  no_neighbors <- which(sapply(nb, function(x) length(x) == 1 && x[1] == 0))\n  cat(fiscal_year, \"- Observations with no neighbors:\", no_neighbors, \"\\n\")\n  \n  if (length(no_neighbors) > 0) {\n    distances <- st_distance(map_data)\n    \n    find_nearest <- function(dist_vector) {\n      sorted_indices <- order(dist_vector)\n      return(sorted_indices[2])\n    }\n    nearest_neighbors <- sapply(no_neighbors, function(i) find_nearest(distances[i,]))\n    \n    for (i in seq_along(no_neighbors)) {\n      nb[[no_neighbors[i]]] <- nearest_neighbors[i]\n    }\n    \n    cat(fiscal_year, \"- Nearest neighbors assigned to observations:\", no_neighbors, \"\\n\")\n    cat(fiscal_year, \"- Assigned nearest neighbors:\", nearest_neighbors, \"\\n\")\n  } else {\n    cat(fiscal_year, \"- All observations have neighbors. No corrections needed.\\n\")\n  }\n  \n  return(nb)\n}\n\ncalculate_morans_i <- function(map_data, nb) {\n  weights <- st_weights(nb, allow_zero = TRUE)\n  map_data$total_cases <- as.numeric(map_data$total_cases)\n  moranI <- global_moran_test(map_data$total_cases, nb, weights, zero.policy = TRUE)\n  \n  global_moran <- global_moran_perm(map_data$total_cases, nb, weights, nsim = 999)\n  \n  return(list(moranI = moranI, global_moran = global_moran))\n}\n\nprocess_year <- function(year, drug_offenses_cleaned, adm1) {\n  drug_offenses_year <- drug_offenses_cleaned %>%\n    filter(fiscal_year == year) %>%\n    group_by(province_en) %>%\n    summarize(total_cases = sum(no_cases, na.rm = TRUE))\n  \n  map_data <- adm1 %>%\n    left_join(drug_offenses_year, by = c(\"ADM1_EN\" = \"province_en\"))\n  \n  map_data <- st_as_sf(map_data)\n  nb_corrected <- correct_neighbors(map_data, year)\n  moranI_result <- calculate_morans_i(map_data, nb_corrected)\n  \n  return(list(map_data = map_data, moranI = moranI_result))\n}\n\nyears <- c(2017, 2019, 2021)\nresults <- lapply(years, function(year) {\n  result <- process_year(year, drug_offenses_cleaned, adm1)\n  cat(\"\\nResults for year\", year, \":\\n\")\n  print(result$moranI$moranI)\n  print(result$moranI$global_moran)\n  return(result)\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2017 - Observations with no neighbors: 67 \n2017 - Nearest neighbors assigned to observations: 67 \n2017 - Assigned nearest neighbors: 66 \n\nResults for year 2017 :\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 2.3717, p-value = 0.008853\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.128902086      -0.013157895       0.003587702 \n\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.1289, observed rank = 979, p-value = 0.042\nalternative hypothesis: two.sided\n\n2019 - Observations with no neighbors: 67 \n2019 - Nearest neighbors assigned to observations: 67 \n2019 - Assigned nearest neighbors: 66 \n\nResults for year 2019 :\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 2.4244, p-value = 0.007668\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.151582766      -0.013157895       0.004617477 \n\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.15158, observed rank = 977, p-value = 0.046\nalternative hypothesis: two.sided\n\n2021 - Observations with no neighbors: 67 \n2021 - Nearest neighbors assigned to observations: 67 \n2021 - Assigned nearest neighbors: 66 \n\nResults for year 2021 :\n\n\tMoran I test under randomisation\n\ndata:  x  \nweights: listw    \n\nMoran I statistic standard deviate = 2.767, p-value = 0.002829\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.195767388      -0.013157895       0.005701229 \n\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.19577, observed rank = 989, p-value = 0.022\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nKey Observations:\n\n**Year 2017 Results**\n\n* Moran’s I statistic: 0.1289\n* P-value (test under randomization): 0.0089\n* Monte Carlo p-value: 0.042\n\nConclusion: For 2017, the positive Moran’s I (0.1289) indicates moderate spatial clustering of drug offenses. The significant p-values (both under randomization and Monte Carlo) suggest that this clustering is not due to random chance, meaning provinces with similar levels of drug offenses tend to be geographically close.\n\n**Year 2019 Results**\n\n* Moran’s I statistic: 0.1516\n* P-value (test under randomization): 0.0077\n* Monte Carlo p-value: 0.046\n\nConclusion: In 2019, the Moran’s I increased to 0.1516, indicating a slightly stronger spatial clustering of drug offenses compared to 2017. Again, the significant p-values suggest that the clustering is statistically significant and not random. This indicates that provinces with higher drug offenses were more clustered in 2019 than in 2017.\n\n**Year 2021 Results**\n\n* Moran’s I statistic: 0.1958\n* P-value (test under randomization): 0.0028\n* Monte Carlo p-value: 0.022\n\nConclusion: By 2021, Moran’s I reached 0.1958, showing an even stronger degree of spatial clustering of drug offenses. The p-values are highly significant, meaning the clustering is strong and consistent. This suggests that by 2021, drug offenses in Thailand were even more spatially concentrated, with neighboring provinces experiencing similar levels of drug offenses.\n\n**Overall Insights**\n\n1. **Increasing Spatial Clustering**: The Moran’s I statistic shows a consistent increase in spatial clustering of drug offenses from 2017 to 2021. This suggests that over time, drug offenses became more geographically concentrated, with neighboring provinces increasingly experiencing similar levels of offenses.\n2. **Statistical Significance**: In all three years, the p-values from both the Moran’s I test and Monte Carlo simulation are below 0.05, indicating that the observed spatial autocorrelation is statistically significant. This means that the clustering of drug offenses across provinces is not random but follows a discernible spatial pattern.\n3. **Policy Implications**: The growing spatial clustering implies that drug offenses are becoming more localized or regionalized. Policymakers and law enforcement agencies might need to focus on regional interventions, particularly in hotspot clusters, to effectively combat drug-related issues.\n\n**Hypothesis Testing**\n\nWe define two hypothesis for our analysis:\n\n* Null Hypothesis ($H_o$): There is no spatial autocorrelation (spatial randomness)\n* Alternative Hypothesis ($H_1$): There is positive spatial autocorrelation (greater than spatial randomness)\n\nThe results from 2017, 2019, and 2021 consistently reject the null hypothesis, confirming the presence of spatial autocorrelation.\n\n### 4.4 Visualization of Results\n\nWe've performed the Moran's I analysis for 2017, 2019, and 2021. Let's visualize the results using histograms of the Monte Carlo simulations and choropleth maps of drug offenses by province for each year.\n\n**Combined Monte-Carlo and Choropleth Plots**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreate_mc_histogram <- function(global_moran, year) {\n  sim_data <- data.frame(sim = global_moran$res)\n  obs_value <- global_moran$statistic\n  \n  ggplot(sim_data, aes(x = sim)) +\n    geom_histogram(bins = 30, fill = \"lightblue\", color = \"black\") +\n    geom_vline(aes(xintercept = obs_value), color = \"red\", linetype = \"dashed\", size = 1) +\n    labs(title = paste(\"Monte Carlo Simulation -\", year),\n         x = \"Moran's I\", y = \"Frequency\") +\n    theme_minimal() +\n    theme(plot.title = element_text(size = 12))\n}\n\ncreate_choropleth <- function(map_data, year) {\n  ggplot(map_data) +\n    geom_sf(aes(fill = total_cases), color = \"white\", size = 0.2) +\n    scale_fill_viridis_c(option = \"plasma\", trans = \"log\", \n                         name = \"Total Cases\\n(log scale)\", \n                         labels = scales::comma) +\n    labs(title = paste(\"Drug Offenses by Province -\", year)) +\n    theme_minimal() +\n    theme(legend.position = \"right\",\n          plot.title = element_text(size = 12))\n}\n\nfor (i in seq_along(years)) {\n  year <- years[i]\n  result <- results[[i]]\n  \n  mc_hist <- create_mc_histogram(result$moranI$global_moran, year)\n  choro_map <- create_choropleth(result$map_data, year)\n  \n  combined_plot <- mc_hist + choro_map +\n    plot_layout(ncol = 2, widths = c(2, 3)) +\n    plot_annotation(\n      title = paste(\"Moran's I Analysis for\", year),\n      theme = theme(plot.title = element_text(size = 16, face = \"bold\", hjust = 0.5))\n    ) &\n    theme(plot.margin = margin(t = 20, r = 10, b = 10, l = 10, unit = \"pt\"))\n  \n  print(combined_plot)\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-26-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-26-3.png){width=672}\n:::\n:::\n\n\n**Interpretation of Results:**\n\nYear 2017:\n\n* Monte Carlo: The observed Moran's I (0.1289) falls significantly to the right of the simulated distribution, suggesting that the spatial clustering of drug offenses in 2017 is higher than what would be expected by random chance. The Monte Carlo p-value (0.042) supports this, confirming spatial autocorrelation is present.\n* Choropleth Map: The map shows provinces in the northern, central, and southern regions of Thailand with the highest concentrations of drug offenses. Notably, Bangkok and some southern provinces stand out as hotspots.\n\nYear 2019:\n\n* Monte Carlo: The observed Moran's I (0.1516) is slightly higher than in 2017, with the red dashed line further to the right, indicating stronger spatial autocorrelation. The p-value (0.046) confirms that the clustering is statistically significant.\n* Choropleth Map: The distribution of drug offenses in 2019 shows a similar pattern to 2017, with more intense clustering in certain northern and central regions. There appears to be a slight increase in cases across northeastern provinces, indicating a growing concentration of offenses.\n\nYear 2021:\n\n* Monte Carlo: The Moran's I value (0.1958) is even higher than in 2019, with the red dashed line clearly separated from the main distribution of simulated values. The p-value (0.022) demonstrates stronger evidence of spatial clustering.\n* Choropleth Map: The map for 2021 shows that the clustering of drug offenses has intensified, particularly in the northeastern and southern regions. The same key provinces remain prominent, but more areas are experiencing high levels of drug offenses, particularly along Thailand's borders.\n\n**Trend of Moran's I Over Years**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran_i_trend <- data.frame(\n  Year = years,\n  MoransI = sapply(results, function(r) r$moranI$moranI$statistic),\n  Pvalue = sapply(results, function(r) r$moranI$moranI$p.value)\n)\n\ny_range <- range(moran_i_trend$MoransI)\ny_padding <- diff(y_range) * 0.1\n\nimproved_trend_chart <- ggplot(moran_i_trend, aes(x = Year, y = MoransI)) +\n  geom_line(size = 1, color = \"blue\") +\n  geom_point(size = 4, color = \"red\") +\n  geom_text(aes(label = sprintf(\"%.3f\\n(p=%.3f)\", MoransI, Pvalue)), \n            vjust = -1.5, hjust = 0.5, size = 3.5) +\n  scale_x_continuous(breaks = years) +\n  scale_y_continuous(limits = c(y_range[1] - y_padding, y_range[2] + y_padding * 3),\n                     labels = scales::label_number(accuracy = 0.001)) +\n  labs(title = \"Trend of Moran's I Over Years\",\n       x = \"Year\", \n       y = \"Moran's I Statistic\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 16, face = \"bold\"),\n    axis.title = element_text(size = 12),\n    axis.text = element_text(size = 10),\n    panel.grid.minor = element_blank()\n  )\n\nprint(improved_trend_chart)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\nThe main takeaway from the trend analysis is the **consistent increase in Moran's I statistic** over the years. This upward trend indicates that spatial autocorrelation of drug offenses has become stronger over time. A higher Moran’s I statistic suggests that provinces with similar levels of drug offenses have become more geographically clustered, and not due to random chance.\n\n## 5.0 Local Measures of Spatial Autocorrelation (LMSA)\n\nMoving on from the global perspective, we will now delve into the local spatial autocorrelation of drug offenses in Thailand. We will use the **Local Moran's I** statistic to identify spatial clusters of high or low drug offenses at the provincial level.\n\n### 5.1 Local Moran's I\n\nLocal Moran's I is a local measure of spatial autocorrelation that evaluates the clustering of similar values in neighboring areas. It provides insights into the spatial patterns of drug offenses at the local level, identifying provinces with significant spatial clustering.\n\nWe start by defining a function to create LISA cluster maps for each year (2017, 2019, 2021) and visualize the local spatial autocorrelation of drug offenses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreate_lisa_map <- function(map_data, year) {\n  ggplot(map_data) +\n    geom_sf(aes(fill = lisa_cluster), color = \"white\", size = 0.1) +\n    scale_fill_manual(\n      values = c(\"High-High\" = \"#D7191C\", \"Low-Low\" = \"#2C7BB6\", \n                 \"Low-High\" = \"#ABD9E9\", \"High-Low\" = \"#FDAE61\",\n                 \"Not Significant\" = \"grey75\"),\n      na.value = \"grey50\",\n      name = \"LISA Cluster Type\",\n      drop = FALSE\n    ) +\n    theme_minimal() +\n    labs(\n      title = \"LISA Cluster Map of Drug Abuse Cases in Thailand\",\n      subtitle = paste(\"Local Moran's I -\", year)\n    ) +\n    theme(\n      plot.title = element_text(size = 16, face = \"bold\", hjust = 0.5),\n      plot.subtitle = element_text(size = 12, hjust = 0.5),\n      legend.position = \"right\",\n      legend.text = element_text(size = 8),\n      axis.text = element_blank(),\n      axis.ticks = element_blank(),\n      panel.grid = element_blank(),\n      panel.background = element_rect(fill = \"aliceblue\")\n    )\n}\n\nyears <- c(2017, 2019, 2021)\nmap_data_list <- list(map_2017_data, map_2019_data, map_2021_data)\n\nfor (i in 1:length(years)) {\n  year <- years[i]\n  map_data <- map_data_list[[i]]\n  \n  cat(\"\\nProcessing year:\", year, \"\\n\")\n  \n  nb <- st_contiguity(map_data)\n  weights <- st_weights(nb, allow_zero = TRUE)\n  map_data$total_cases <- as.numeric(map_data$total_cases)\n  \n  local_moran_results <- local_moran(\n    map_data$total_cases,\n    nb,\n    weights,\n    nsim = 999,\n    zero.policy = TRUE\n  )\n  \n  map_data <- map_data %>%\n    mutate(\n      local_moran_i = local_moran_results$Ii,\n      local_moran_p = local_moran_results$p_folded_sim,\n      local_moran_z = local_moran_results$Z.Ii\n    )\n  \n  map_data <- map_data %>%\n    mutate(\n      case_lag = st_lag(total_cases, nb, weights),\n      case_scale = scale(total_cases),\n      lag_scale = scale(case_lag),\n      lisa_cluster = case_when(\n        local_moran_p > 0.05 ~ \"Not Significant\",\n        case_scale > 0 & lag_scale > 0 ~ \"High-High\",\n        case_scale < 0 & lag_scale < 0 ~ \"Low-Low\",\n        case_scale > 0 & lag_scale < 0 ~ \"High-Low\",\n        case_scale < 0 & lag_scale > 0 ~ \"Low-High\"\n      )\n    )\n  \n  lisa_map <- create_lisa_map(map_data, year)\n  print(lisa_map)\n  \n  cat(\"Summary of LISA clusters for\", year, \":\\n\")\n  print(table(map_data$lisa_cluster))\n  cat(\"\\n\")\n  \n  assign(paste0(\"local_moran_\", year), list(\n    map_data = map_data,\n    local_moran_results = local_moran_results\n  ))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProcessing year: 2017 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in spdep::poly2nb(geometry, queen = queen, ...): some observations have no neighbours;\nif this seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in spdep::poly2nb(geometry, queen = queen, ...): neighbour object has 2 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `stopifnot()`.\nℹ In argument: `case_lag = st_lag(total_cases, nb, weights)`.\nCaused by warning in `spdep::lag.listw()`:\n! NAs in lagged values\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary of LISA clusters for 2017 :\n\n      High-High        Low-High         Low-Low Not Significant \n              5               1               8              62 \n\n\nProcessing year: 2019 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in spdep::poly2nb(geometry, queen = queen, ...): some observations have no neighbours;\nif this seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in spdep::poly2nb(geometry, queen = queen, ...): neighbour object has 2 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `stopifnot()`.\nℹ In argument: `case_lag = st_lag(total_cases, nb, weights)`.\nCaused by warning in `spdep::lag.listw()`:\n! NAs in lagged values\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary of LISA clusters for 2019 :\n\n      High-High        Low-High         Low-Low Not Significant \n              3               3               4              66 \n\n\nProcessing year: 2021 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in spdep::poly2nb(geometry, queen = queen, ...): some observations have no neighbours;\nif this seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in spdep::poly2nb(geometry, queen = queen, ...): neighbour object has 2 sub-graphs;\nif this sub-graph count seems unexpected, try increasing the snap argument.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There was 1 warning in `stopifnot()`.\nℹ In argument: `case_lag = st_lag(total_cases, nb, weights)`.\nCaused by warning in `spdep::lag.listw()`:\n! NAs in lagged values\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-28-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-28-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary of LISA clusters for 2021 :\n\n      High-High        Low-High         Low-Low Not Significant \n              2               2              10              62 \n```\n\n\n:::\n:::\n\n\nGeneral Observations:\n\n1. **High-High Clusters**: These regions are hotspots of drug offenses with high values surrounded by other high values. In 2017, there are 5 high-high clusters, concentrated around Bangkok and neighboring provinces, as well as a small concentration in southern Thailand. In 2019, the high-high clusters have reduced to 3 provinces, with the cluster near Bangkok shrinking, though the southern cluster persists. By 2021, only 2 provinces remain in the high-high category. The southern provinces remain a significant hotspot, showing persistent high levels of drug abuse.\n2. **Low-Low Clusters**: Areas with low levels of drug abuse and are surrounded by other low-level provinces are considered coldspots. In 2017, there are 8 low-low clusters, mostly located in the northern and northeastern regions of Thailand. By 2019, the number of low-low clusters drops to 4 provinces, indicating a reduction in coldspots, though they remain in the same regions. However, by 2021, the number of low-low clusters rises again to 10 provinces, spread across the same general northern and northeastern regions.\n3. **High-Low and Low-High Clusters**: These clusters represent areas with high values surrounded by low values and vice versa. The presence of these clusters indicates a mix of high and low drug abuse levels in neighboring provinces. The number of high-low and low-high clusters fluctuates across the years, suggesting changes in the spatial distribution of drug offenses.\n\nObservable Trends:\n\n1. **Decreasing High-High Clusters**: The number of high-high clusters decreases over time, with a notable reduction near Bangkok. However, the southern region remains consistently problematic, suggesting that while some regions are improving, others continue to struggle with high levels of drug abuse.\n2. **Stable Low-Low Clusters**: Northern and northeastern provinces have consistently shown lower levels of drug abuse, with more provinces joining the low-low cluster in 2021. This stability suggests that these regions are relatively unaffected by the drug abuse crisis compared to other parts of the country.\n3. **Persistence of Southern Hotspots**: The southern provinces, specifically around Phuket and nearby provinces, have consistently shown high levels of drug abuse. \n\n### 5.2 Trend Analysis of Local Moran's I\n\nLet's shift the focus from the Local Moran's I over the years to the individual provinces. We will create a line plot to visualize the trend of Local Moran's I for the top 5 provinces with the highest average Local Moran's I values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreate_local_moran_trend <- function(data_list, top_n = 5) {\n  combined_data <- bind_rows(\n    lapply(seq_along(data_list), function(i) {\n      data.frame(\n        ADM1_EN = data_list[[i]]$map_data$ADM1_EN,\n        local_moran_i = data_list[[i]]$local_moran_results$ii,\n        year = years[i]\n      )\n    })\n  )\n  \n  top_provinces <- combined_data %>%\n    group_by(ADM1_EN) %>%\n    summarize(avg_local_moran = mean(local_moran_i, na.rm = TRUE)) %>%\n    top_n(top_n, avg_local_moran) %>%\n    pull(ADM1_EN)\n  \n  ggplot(combined_data %>% filter(ADM1_EN %in% top_provinces), \n         aes(x = year, y = local_moran_i, color = ADM1_EN, group = ADM1_EN)) +\n    geom_line() +\n    geom_point() +\n    labs(title = paste(\"Trend of Local Moran's I for Top\", top_n, \"Provinces\"),\n         x = \"Year\", y = \"Local Moran's I\",\n         color = \"Province\") +\n    theme_minimal() +\n    theme(legend.position = \"right\")\n}\n\ndata_list <- list(local_moran_2017, local_moran_2019, local_moran_2021)\n\ntrend_plot <- create_local_moran_trend(data_list)\nprint(trend_plot)\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nGeneral Observations:\n\n1. **Bangkok's Absence**: Bangkok, a notable hotspot for drug activity, is notably absent from the top 5 provinces based on Local Moran's I. This indicates that drug abuse issues in Bangkok may be more isolated or self-contained rather than spatially linked to surrounding regions.\n2. **Focus Shifting to Other Provinces**: The top 5 provinces shown here may have relatively lower overall numbers of offenses than Bangkok, but the spatial clustering in these regions is stronger. This points to regional patterns of drug abuse that are concentrated and linked to neighboring provinces in ways that are not as apparent in Bangkok.\n\nProvincial Analysis:\n\n1. **Central Provinces**: Samut Prakan stands out amongst the other 4 provinces, as it is the only one with a very sharp spike in 2019 with its Local Moran’s I rising significantly before dropping back in 2021. This indicates a sudden, strong spatial clustering of drug offenses during 2019, possibly due to a regional incident or change in trafficking patterns.\n2. **Southern Provinces**: Nakhon Si Thammarat, Surat Thani, and Songkhla are prominent in the analysis, reinforcing the idea that southern Thailand is a critical region for drug-related activities and spatial clustering. This region's consistent appearance in spatial analyses indicates that drug offenses in the south are highly regionalized and should be a priority for targeted interventions.\n3. **Absence of Northern Provinces**: Interestingly, no northern provinces are represented in the top 5 based on Local Moran's I, suggesting that the drug offense patterns in the north are not as spatially clustered with their neighbors, despite being consistently low in total cases.\n\n### 5.3 Hotspot and Coldspot Analysis\n\nThe Gi\\* statistic (Getis-Ord Gi\\*) is used to identify local clusters of high and low values in the data, helping us detect hotspots (high values) and cold spots (low values) for drug abuse across Thailand. \n\nThe p-value maps indicate the statistical significance of these clusters, showing where the Gi\\* values are most likely not due to random chance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreate_gi_star_and_pvalue_plots <- function(map_data, nb, weights, year) {\n  suppressWarnings(\n    gi_stars <- local_g_perm(\n      map_data$total_cases,\n      nb,\n      weights,\n      nsim = 999\n    )\n  )\n\n  map_data$gi_star <- gi_stars$gi \n  map_data$p_value <- gi_stars$p_folded_sim\n  \n  gi_plot <- ggplot(map_data) +\n    geom_sf(aes(fill = gi_star), color = \"white\", size = 0.1) +\n    scale_fill_gradient2(\n      low = \"blue\", mid = \"white\", high = \"red\", \n      midpoint = 0, name = \"Gi*\",\n      limits = c(min(map_data$gi_star), max(map_data$gi_star))\n    ) +\n    theme_minimal() +\n    labs(title = paste(\"Gi* Statistic -\", year)) +\n    theme(\n      legend.position = \"right\",\n      legend.key.height = unit(1, \"cm\"),\n      legend.text = element_text(size = 8),\n      axis.text = element_blank(),\n      axis.ticks = element_blank(),\n      panel.grid = element_blank(),\n      plot.margin = margin(5, 5, 5, 5)\n    )\n  \n  p_plot <- ggplot(map_data) +\n    geom_sf(aes(fill = cut(p_value, breaks = c(0, 0.001, 0.01, 0.05, 1), \n                         labels = c(\"<= 0.001\", \"<= 0.01\", \"<= 0.05\", \"Not sig\"))), \n          color = \"white\", size = 0.1) +\n  scale_fill_manual(\n    values = c(\"#d7191c\", \"#fdae61\", \"#ffffbf\", \"#2c7bb6\"),\n    name = \"p-value\"\n  ) +\n  theme_minimal() +\n  labs(title = paste(\"p-value of Gi* -\", year)) +\n  theme(\n    legend.position = \"right\",\n    legend.key.height = unit(1, \"cm\"),\n    legend.text = element_text(size = 8),\n    legend.title = element_text(size = 10),\n    axis.text = element_blank(),\n    axis.ticks = element_blank(),\n    panel.grid = element_blank(),\n    plot.margin = margin(5, 5, 5, 5)\n  )\n  \n  combined_plot <- gi_plot + p_plot +\n    plot_layout(ncol = 2, widths = c(1, 1.2)) +\n    plot_annotation(\n      title = paste(\"Gi* and p-value Analysis of Drug Abuse Cases in Thailand -\", year),\n      theme = theme(plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5))\n    )\n  \n  return(combined_plot)\n}\n\nfor (i in seq_along(years)) {\n  year <- years[i]\n  data <- get(paste0(\"local_moran_\", year))\n  plot <- create_gi_star_and_pvalue_plots(data$map_data, nb, weights, year)\n  print(plot)\n}\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-30-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-30-3.png){width=672}\n:::\n:::\n\n\nGeneral Observations:\n\n1. **Gi\\* Statistic**: \n  * 2017: In 2017, Bangkok and nearby central provinces show the highest Gi\\* values, indicating a strong cluster of drug abuse in this area. The southern provinces also show elevated Gi\\* values, indicating another emerging hotspot in the south. Some provinces in northern Thailand show relatively low Gi\\* values, suggesting potential cold spots for drug abuse.\n  * 2019: The Bangkok region remains a hotspot, and southern provinces continue to show high Gi\\* values, indicating persistent clustering of drug abuse cases in these areas. More central provinces are now involved in this cluster, suggesting an expansion of the problem. Northern provinces maintain their low Gi\\* values, reinforcing their cold spot status.\n  * 2021: The southern provinces around Phuket and Surat Thani show the strongest Gi values\\*, now becoming the most significant hotspot. Bangkok’s influence seems to have decreased slightly, though it remains significant. The north of Thailand shows increasingly low Gi values\\*, reinforcing its position as a cold spot for drug abuse cases.\n2. **p-value Analysis**:\n  * 2017: In 2017, the Bangkok region and nearby provinces exhibit a highly significant hotspot (p ≤ 0.01), confirming that the clustering in this region is unlikely to be due to chance. Central Thailand shows some expansion of this significant cluster. \n  * 2019: By 2019, the significant hotspot in the Bangkok region persists, while the southern region is now showing moderate significance (p ≤ 0.05), suggesting it is emerging as a more prominent hotspot.\n  * 2021: In 2021, southern Thailand becomes the most significant hotspot for drug abuse (p ≤ 0.001), with the Bangkok region maintaining significance but slightly lower compared to the south. Central Thailand also remains significant, but with a reduced footprint. Most northern regions are now non-significant.\n\nTrend Analysis:\n\n1. **Shift of Hotspots**: Over time, there has been a shift in significant hotspots from Bangkok and central Thailand in 2017 to the southern provinces by 2021.\n2. **Persistent Cold Spots in Northern Thailand**: Across all three years, northern provinces consistently show low Gi\\* values and non-significant p-values. This reinforces that drug abuse is less of a problem in the north, with fewer clusters of high drug abuse activity.\n3. **Emerging Central Region Influence**: Central Thailand, particularly the provinces surrounding Bangkok, show a consistent presence of significant clustering, though the intensity fluctuates. This suggests that drug abuse issues in central Thailand are more persistent and widespread.\n4. **Critical Southern Region**: The southern provinces, particularly those around Phuket and Surat Thani, have emerged as the most critical region for drug abuse by 2021, with statistically significant clusters. From a law enforcement perspective, this represents a key area for targeted interventions.\n\n### 5.4 Identification of Hotspots and Coldspots\n\nTo better understand the consistent hotspots and coldspots across the years, we will identify provinces that have consistently shown high or low clustering of drug offenses. We will then visualize these consistent spots on a map to highlight the regions that have remained problematic or less affected over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentify_hot_cold_spots <- function(local_moran_data, year) {\n  map_data <- local_moran_data$map_data\n  moran_results <- local_moran_data$local_moran_results\n  \n  combined_data <- cbind(map_data, moran_results)\n  \n  hot_spots <- combined_data %>%\n    filter(lisa_cluster == \"High-High\" & p_folded_sim <= 0.05) %>%\n    arrange(desc(ii)) %>%\n    pull(ADM1_EN)\n  \n  cold_spots <- combined_data %>%\n    filter(lisa_cluster == \"Low-Low\" & p_folded_sim <= 0.05) %>%\n    arrange(ii) %>%\n    pull(ADM1_EN)\n  \n  cat(\"\\nYear:\", year, \"\\n\")\n  cat(\"Hot Spots (High-High clusters):\", paste(hot_spots, collapse = \", \"), \"\\n\")\n  cat(\"Cold Spots (Low-Low clusters):\", paste(cold_spots, collapse = \", \"), \"\\n\\n\")\n  \n  return(list(hot_spots = hot_spots, cold_spots = cold_spots))\n}\n\nall_spots <- list()\n\nfor (year in years) {\n  data <- get(paste0(\"local_moran_\", year))\n  spots <- identify_hot_cold_spots(data, year)\n  all_spots[[as.character(year)]] <- spots\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nYear: 2017 \nHot Spots (High-High clusters): Samut Prakan, Chachoengsao, Nakhon Pathom, Pathum Thani, Nonthaburi \nCold Spots (Low-Low clusters): Suphan Buri, Phrae, Nakhon Sawan, Kamphaeng Phet, Phitsanulok, Sukhothai, Uttaradit, Chai Nat \n\n\nYear: 2019 \nHot Spots (High-High clusters): Samut Prakan, Pathum Thani, Nonthaburi \nCold Spots (Low-Low clusters): Kamphaeng Phet, Phitsanulok, Nakhon Sawan, Chai Nat \n\n\nYear: 2021 \nHot Spots (High-High clusters): Nakhon Si Thammarat, Samut Prakan \nCold Spots (Low-Low clusters): Nakhon Sawan, Suphan Buri, Kamphaeng Phet, Kanchanaburi, Ratchaburi, Sing Buri, Phetchaburi, Chai Nat, Uthai Thani, Samut Songkhram \n```\n\n\n:::\n\n```{.r .cell-code}\nfind_consistent_spots <- function(all_spots, years) {\n  consistent_hot <- Reduce(intersect, lapply(years, function(y) all_spots[[as.character(y)]]$hot_spots))\n  consistent_cold <- Reduce(intersect, lapply(years, function(y) all_spots[[as.character(y)]]$cold_spots))\n  \n  cat(\"Consistent Hot Spots across all years:\", paste(consistent_hot, collapse = \", \"), \"\\n\")\n  cat(\"Consistent Cold Spots across all years:\", paste(consistent_cold, collapse = \", \"), \"\\n\")\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfind_consistent_spots(all_spots, years)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConsistent Hot Spots across all years: Samut Prakan \nConsistent Cold Spots across all years: Nakhon Sawan, Kamphaeng Phet, Chai Nat \n```\n\n\n:::\n\n```{.r .cell-code}\nvisualize_consistent_spots <- function(map_data, consistent_hot, consistent_cold) {\n  map_data$consistent_spots <- case_when(\n    map_data$ADM1_EN %in% consistent_hot ~ \"Hot Spot\",\n    map_data$ADM1_EN %in% consistent_cold ~ \"Cold Spot\",\n    TRUE ~ \"Not Consistent\"\n  )\n  \n  ggplot(map_data) +\n    geom_sf(aes(fill = consistent_spots), color = \"white\", size = 0.1) +\n    scale_fill_manual(\n      values = c(\"Hot Spot\" = \"red\", \"Cold Spot\" = \"blue\", \"Not Consistent\" = \"grey\"),\n      name = \"Consistent Spots\"\n    ) +\n    theme_minimal() +\n    labs(title = \"Consistent Hot and Cold Spots (2017-2021)\") +\n    theme(\n      legend.position = \"right\",\n      axis.text = element_blank(),\n      axis.ticks = element_blank(),\n      panel.grid = element_blank()\n    )\n}\n\nrecent_map_data <- local_moran_2021$map_data\nconsistent_hot <- all_spots[[\"2021\"]]$hot_spots\nconsistent_cold <- all_spots[[\"2021\"]]$cold_spots\nprint(visualize_consistent_spots(recent_map_data, consistent_hot, consistent_cold))\n```\n\n::: {.cell-output-display}\n![](THE02_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nKey Observations:\n\n1. **Persistent Hot Spot**: Samut Prakan is the only province that has consistently been a hot spot for drug abuse across all three years (2017, 2019, and 2021).\n2. **Cold Spot Stability**: The provinces of Suphan Buri, Nakhon Sawan, and Chai Nat have consistently low drug abuse rates. These provinces may offer insights into successful strategies for keeping drug abuse under control. \n3. **Shift in Hot Spots**: In 2017, the hot spots included multiple provinces in central Thailand but by 2021, the focus has shifted primarily to the southern province of Nakhon Si Thammarat. This shift highlights a changing landscape of drug abuse problems over time, where southern Thailand is becoming a more critical area for attention in 2021.\n4. **Expansion of Cold Spots**: In 2021, cold spots have expanded, particularly in the western and central provinces. This suggests that drug abuse is being controlled effectively in more regions over time, leading to the expansion of areas with consistently low drug abuse rates.\n\n## 6.0 Bonus: \n\n## 7.0 Conclusion\n\nThe analysis of the spatial distribution of drug offenses in Thailand provides valuable insights into the regional patterns and clustering of drug abuse cases. By utilizing spatial autocorrelation techniques such as Moran's I, LISA, and Gi\\* statistics, we were able to identify hotspots, cold spots, and consistent clusters of drug offenses across the country.\n\n1. **Temporal Trends**: The analysis revealed a consistent increase in spatial clustering of drug offenses over the years, with certain regions showing persistent high levels of drug abuse. The southern provinces, in particular, emerged as a critical hotspot for drug-related activities.\n2. **Regional Consistencies**: Southern Thailand, central provinces around Bangkok, and the northeastern region consistently showed high levels of drug offenses. These areas require targeted interventions to address the drug abuse crisis effectively.\n3. **Policy Implications**: The identification of hotspots and cold spots can inform policymakers and law enforcement agencies about the spatial distribution of drug offenses. By focusing on regions with high clustering, authorities can implement targeted strategies to combat drug trafficking and abuse effectively.\n4. **Future Directions**: Further research could explore the underlying factors contributing to the spatial clustering of drug offenses, such as socio-economic conditions, law enforcement strategies, and drug trafficking routes. Understanding these factors can help develop more effective policies to address the drug abuse crisis in Thailand.\n\nWe can also conclude from our hypotheses that the spatial distribution of drug offenses in Thailand is not random but exhibits significant clustering patterns. The presence of spatial autocorrelation indicates that provinces with similar levels of drug offenses tend to be geographically close, suggesting underlying factors contributing to the spatial clustering of drug abuse.\n\n## References\n\n1. Claude AI. (n.d.). Claude AI. https://claude.ai/\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "THE02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}