project:
  type: website
  render:
    - "*.qmd"
    - "!data/**"
    - "Ex01.qmd"
    - "Ex03.qmd"
    - "Ex02.qmd"
    - "Ex05.qmd"
    - "ICE01.qmd"
    - "ICE02.qmd"
    - "ICE03.qmd"
    - "ICE04.qmd"
    - "THE01.qmd"

website:
  title: "IS415 Geospatial Analytics"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "HandsOnEx/Ex01/Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "HandsOnEx/Ex02/Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "HandsOnEx/Ex03/Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "InClassEx/ICE04/ICE04.html"
          - text: "Hands-on Exercise 5"
            href: "HandsOnEx/Ex05/Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "HandsOnEx/Ex06/Ex06.html"
      - text: "In Class Exercise"
        menu:
          - text: "In Class Exercise 1"
            href: "InClassEx/ICE01/ICE01.html"
          - text: "In Class Exercise 2"
            href: "InClassEx/ICE02/ICE02.html"
          - text: "In Class Exercise 3"
            href: "InClassEx/ICE03/ICE03.html"
          - text: "In Class Exercise 4"
            href: "InClassEx/ICE04/ICE04.html"
          - text: "In Class Exercise 5"
            href: "InClassEx/ICE05/ICE05.html"
      - text: "Take Home Exercise"
        menu:
          - text: "Take Home Exercise 1"
            href: "TakehomeEx/THE01/THE01.html"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-title: "Outline"

editor: source
