project:
  type: website

website:
  title: "IS415 Geospatial Analytics"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "HandsOnEx/Ex01/Ex01.html"
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-title: "Outline"

editor: visual
