---
title: "In Class Exercise 4"
author: "Bao Jie Yeo"
date: '2024-09-09'
last-modified: '2024-09-09'
---

## Loading Packages

```{r}
pacman::p_load(sf, raster, spatstat, sparr, tmap, tidyverse)
```

## Import and Prepare Study Area

```{r}
kbb_sf <- st_read(dsn="data/rawdata",
               layer="Kepulauan_Bangka_Belitung") |>
  st_union() |>
  st_zm(drop=TRUE, what="ZM") |>
  st_transform(crs=32748)
```

```{r}
kbb_owin <- as.owin(kbb_sf)
kbb_owin
```

```{r}
class(kbb_owin)
```

```{r}
fire_sf <- read.csv("data/rawdata/forestfires.csv") %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>%
  st_transform(crs = 32748)
fire_sf
```

```{r}
fire_sf <- fire_sf |>
  mutate(DayOfYear = yday(acq_date)) |>
  mutate(Month_num = month(acq_date)) |>
  mutate(Month_fac = month(acq_date,
                           label = TRUE,
                           abbr = FALSE))
```

```{r}
tm_shape(kbb_sf) +
  tm_polygons() +
  tm_shape(fire_sf) +
  tm_dots()
```

```{r}
tm_shape(kbb_sf) +
  tm_polygons() +
  tm_shape(fire_sf) +
  tm_dots(size=0.1) +
  tm_facets(by="Month_fac",
            free.coords=FALSE,
            drop.units=TRUE)
```

```{r}
fire_month <- fire_sf |>
  select(Month_num)
fire_month
```

```{r}
fire_month_ppp <- as.ppp(fire_month)
fire_month_ppp
```

```{r}
summary(fire_month_ppp)
```

```{r}
fire_month_owin <- fire_month_ppp[kbb_owin]
summary(fire_month_owin)
```

```{r}
plot(fire_month_owin)
```

```{r}
st_kde <- spattemp.density(fire_month_owin)
summary(st_kde)
```

```{r}
tims <- c(7,8,9,10,11,12)
par(mfcol=c(2,3))
for(i in tims) {
  plot(st_kde, i,
       override.par=FALSE,
       fix.range=TRUE,
       main=paste("KDE at month", i))
}
```
```{r}
fire_yday_ppp <- fire_sf |>
  select(DayOfYear) |>
  as.ppp()
```


```{r}
fire_yday_owin <- fire_yday_ppp[kbb_owin]
summary(fire_yday_owin)
```

```{r}
kde_yday <- spattemp.density(fire_yday_owin)
summary(kde_yday)
```
Limit plot kde_yday to specific days e.g. 30, 60, 90, 120, 150, 180
```{r}
tims <- c(30,60,90,120,150,180,210,240,270,300,330,352)
par(mfcol=c(2,3))
for(i in tims) {
  plot(kde_yday, i,
       override.par=FALSE,
       fix.range=TRUE,
       main=paste("KDE at day", i))
}
```

```{r}
set.seed(42)
BOOT.spattemp(fire_yday_owin)
```


```{r}
tims <- c(30,60,90,120,150,180,210,240,270,300,307,352)
par(mfcol=c(2,3))
for(i in tims) {
  plot(kde_yday, i,
       override.par=FALSE,
       fix.range=TRUE,
       main=paste("KDE at day", i))
}
```

```{r}
# | echo: false
# | eval: false
library(animation)
library(spatstat)

data(fmd)
fmd_case <- fmd$cases
fmd_cont <- fmd$controls

# Estimate bandwidths and create density/risk maps
hlam <- LIK.spattemp(fmd_case)
f.breve <- spattemp.density(fmd_case, h=hlam[1], lambda=hlam[2], tlim=c(10, 352))
g.tilde <- bivariate.density(fmd_cont, h0=hlam[1])
rho.breve <- spattemp.risk(f=f.breve, g=g.tilde, tolerate=TRUE)
```